In [2]:
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):

      super().__init__()
      self.linear = nn.Linear(num_features, 1)
      self.sigmoid = nn.Sigmoid()

    def forward(self, x):

      out = self.linear(x)
      out = self.sigmoid(out)

      return out

# model created





In [3]:
# create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#for forward pass
model(features)

tensor([[0.4169],
        [0.3663],
        [0.4295],
        [0.3826],
        [0.3736],
        [0.4068],
        [0.4345],
        [0.3857],
        [0.3372],
        [0.3805]], grad_fn=<SigmoidBackward0>)

In [4]:
model.linear.weight

Parameter containing:
tensor([[-0.1395, -0.3679, -0.0492,  0.1570,  0.3134]], requires_grad=True)

In [5]:
!pip install torchinfo

In [7]:
import torchinfo as torchinfo

torchinfo.summary(model=model, input_data=features)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [10]:


class Model(nn.Module):

    def __init__(self, num_features):

      super().__init__()
      self.linear1 = nn.Linear(num_features, 3)
      self.relu = nn.ReLU()
      self.linear2 = nn.Linear(3, 1)
      self.sigmoid = nn.Sigmoid()

    def forward(self, x):

      out = self.linear1(x)
      out = self.relu(out)
      out = self.linear2(out)
      out = self.sigmoid(out)


      return out

# model created





In [11]:
# create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#for forward pass
model(features)

tensor([[0.3732],
        [0.3790],
        [0.3805],
        [0.3945],
        [0.3842],
        [0.3801],
        [0.3940],
        [0.3821],
        [0.3843],
        [0.3869]], grad_fn=<SigmoidBackward0>)

In [12]:
import torchinfo as torchinfo

torchinfo.summary(model=model, input_data=features)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [13]:


class Model(nn.Module):

    def __init__(self, num_features):

      super().__init__()
      self.network = nn.Sequential(
          nn.Linear(num_features, 3),
          nn.ReLU(),
          nn.Linear(3, 1),
          nn.Sigmoid(),
      )


    def forward(self, x):

      out = self.network(x)


      return out

# model created





In [14]:
# create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#for forward pass
model(features)

tensor([[0.4071],
        [0.4040],
        [0.4087],
        [0.4135],
        [0.3976],
        [0.4053],
        [0.4095],
        [0.4062],
        [0.3982],
        [0.3963]], grad_fn=<SigmoidBackward0>)

In [15]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [17]:
from google.colab import files

# This will open a file picker on Colab to select file(s) from your desktop
uploaded = files.upload()

# Save uploaded files into the Colab directory
for filename in uploaded.keys():
    print(f'Saved file: {filename}')


Saving breast-cancer.csv to breast-cancer.csv
Saved file: breast-cancer.csv


In [18]:
df = pd.read_csv("breast-cancer.csv")

In [19]:
df.drop(columns=['id'], inplace = True)

In [20]:
X = df.iloc[:, 1:]               # all numeric
y = df.iloc[:, 0]                # 'diagnosis' column (object)

In [21]:
le = LabelEncoder()
y_label = le.fit_transform(y)

In [30]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y_label, test_size=0.2, random_state=42
)

In [31]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [34]:
# If X_train is a DataFrame, convert it
X_train_tensor = torch.from_numpy(X_train.to_numpy().astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.to_numpy().astype(np.float32))

# If y_train/y_test are already NumPy arrays, use them directly
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))



In [35]:
import torch.nn as nn

class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out



In [26]:
learning_rate = 0.1
epochs = 25

In [27]:
#define lossfunction
loss_function = nn.BCELoss()

#Traning

In [36]:
model = MySimpleNN(X_train_tensor.shape[1])

#define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# loop
for epoch in range(epochs):

  #forward pass
  y_pred = model(X_train_tensor)

  #calc loss
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  #clear gradient
  optimizer.zero_grad()

  #backward pass
  loss.backward()

  #parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 62.85714340209961
Epoch: 2, Loss: 62.85714340209961
Epoch: 3, Loss: 62.85714340209961
Epoch: 4, Loss: 62.85714340209961
Epoch: 5, Loss: 62.85714340209961
Epoch: 6, Loss: 62.85714340209961
Epoch: 7, Loss: 62.85714340209961
Epoch: 8, Loss: 62.85714340209961
Epoch: 9, Loss: 62.85714340209961
Epoch: 10, Loss: 62.85714340209961
Epoch: 11, Loss: 62.85714340209961
Epoch: 12, Loss: 62.85714340209961
Epoch: 13, Loss: 62.85714340209961
Epoch: 14, Loss: 62.85714340209961
Epoch: 15, Loss: 62.85714340209961
Epoch: 16, Loss: 62.85714340209961
Epoch: 17, Loss: 62.85714340209961
Epoch: 18, Loss: 62.85714340209961
Epoch: 19, Loss: 62.85714340209961
Epoch: 20, Loss: 62.85714340209961
Epoch: 21, Loss: 62.85714340209961
Epoch: 22, Loss: 62.85714340209961
Epoch: 23, Loss: 62.85714340209961
Epoch: 24, Loss: 62.85714340209961
Epoch: 25, Loss: 62.85714340209961


In [37]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.37719297409057617
