## Topics:

What is a Tensor?

Tensor creation (torch.tensor(), torch.rand())

Tensor operations (reshaping, slicing, math ops)

Moving tensors to GPU (.to(device))



In [2]:
import torch
print(torch.__version__)


2.6.0+cu124


In [3]:
if torch.cuda.is_available():
  print("gpu available")
  print(f"using GPU : {torch.cuda.get_device_name(0)}")
else:
  print("using CPU")

using CPU


# Creating a Tensor

In [4]:
#uisng empty
a = torch.empty(2,3)

In [5]:
type(a)

torch.Tensor

In [6]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(2,3)

tensor([[0.0505, 0.2085, 0.8953],
        [0.1283, 0.3291, 0.9007]])

In [9]:
 ##for same random value
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])

# Shapes

In [14]:
x.shape


torch.Size([2, 3])

In [15]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [16]:
torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

# Mathematical Operations

In [17]:
x + 2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [18]:
x // 2

tensor([[0, 1, 1],
        [2, 2, 3]])

In [19]:
torch.round(x) # touch.ceil(x), floor(x),

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
torch.clamp(x, min=2, max=4)

tensor([[2, 2, 3],
        [4, 4, 4]])

# Reduction Operation

In [21]:
torch.sum(x)

tensor(21)

In [22]:
#column wise
torch.sum(x, dim=0)

tensor([5, 7, 9])

In [23]:
torch.mean(x)  # median(), max(), min(), prod(), std(), var()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [24]:
# argmax position of maxvalue
torch.argmax(x)

tensor(5)

# Matrix operation

In [25]:
f = torch.randint(size=(2,3),low=0,high=10)
g = torch.randint(size=(3,2),low=1,high=20)


In [26]:
torch.matmul(f,g) #matrix operation

tensor([[134, 144],
        [ 38,  53]])

In [27]:
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([1,2,3])

In [28]:
torch.dot(vector1, vector2) #dot product

tensor(14)

In [29]:
# torch.transpose(f, 0, 1) torch.det(h)


In [30]:
## Comparison
f = torch.randint(size=(3,2),low=0,high=10)
g = torch.randint(size=(3,2),low=1,high=20)
f == g

tensor([[False, False],
        [False, False],
        [False,  True]])

# Special function

In [8]:
f = torch.randint(size=(3,2),low=0,high=10, dtype=torch.float32)
f

tensor([[2., 6.],
        [7., 6.],
        [2., 0.]])

In [32]:
torch.log(f)

tensor([[1.9459,   -inf],
        [  -inf, 2.1972],
        [1.6094, 1.9459]])

In [33]:
torch.sigmoid(f)

tensor([[0.9991, 0.5000],
        [0.5000, 0.9999],
        [0.9933, 0.9991]])

In [34]:
torch.softmax(f, dim=0)

tensor([[8.8009e-01, 1.0869e-04],
        [8.0254e-04, 8.8070e-01],
        [1.1911e-01, 1.1919e-01]])

In [35]:
torch.relu(f)

tensor([[7., 0.],
        [0., 9.],
        [5., 7.]])

# Inplace Operation

In [36]:
f.add_(g)  ## no new gtensor is created

tensor([[20., 15.],
        [ 5., 21.],
        [22., 13.]])

In [37]:
id(f)

138927195907824

# Copying a tensor

In [38]:
b = f.clone() ## a = b

In [39]:
b

tensor([[20., 15.],
        [ 5., 21.],
        [22., 13.]])

# Tensor Operation

In [3]:
torch.cuda.is_available()

True

In [4]:
device = torch.device('cuda')

In [6]:
torch.rand((2,3), device=device) #////creating a new temsor in GPU

tensor([[0.3919, 0.0972, 0.7931],
        [0.6309, 0.0133, 0.5746]], device='cuda:0')

In [48]:
#Moving an exsisting tensor to GPU
# f.to(device)

In [9]:
f.to(device) #by default, this tensor lives on the CPU.

tensor([[2., 6.],
        [7., 6.],
        [2., 0.]], device='cuda:0')

# Reshaping

In [12]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
a.reshape(2,2,2,2) #reshape

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [15]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
b = torch.rand(2,3,4)
b

tensor([[[0.4395, 0.7701, 0.6521, 0.6146],
         [0.5510, 0.4750, 0.8021, 0.1159],
         [0.5272, 0.9338, 0.2697, 0.0438]],

        [[0.9121, 0.9852, 0.9662, 0.0525],
         [0.3282, 0.0565, 0.3052, 0.1175],
         [0.2542, 0.5830, 0.2822, 0.6484]]])

In [22]:
# permute
b.permute(2,1,0).size()

torch.Size([4, 3, 2])

In [23]:
# Unsqueeze ...basically add new dimention on postion/indx
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [25]:
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# TO Numpy

In [26]:
import numpy as np

In [28]:
p = torch.tensor([1,2,3])
p


tensor([1, 2, 3])

In [30]:
l = p.numpy()
l

array([1, 2, 3])

In [32]:
type(l) # tensor to numpy

numpy.ndarray

In [33]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [34]:
torch.from_numpy(c)

tensor([1, 2, 3])